# Generated by Django 4.2.5 on 2023-09-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('reading_time', models.FloatField()),
                ('summary', models.CharField(max_length=1000)),
                ('notes', models.CharField(max_length=2000)),
                ('related_links', models.CharField(max_length=100)),
            ],
        ),
    ]
